#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DB_POSTGRES_USER" --dbname "$POSTGRES_DB_NAME" <<-EOSQL
    CREATE USER "$DB_POSTGRES_USER" WITH ENCRYPTED PASSWORD "$DB_POSTGRES_PASSWORD";
    CREATE DATABASE "$DB_POSTGRES_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$DB_POSTGRES_NAME" TO "$DB_POSTGRES_USER";
EOSQL